services:
  remux:
    image: ghcr.io/lostb1t/remux:0.29.0
    container_name: remux
    restart: unless-stopped
    network_mode: "container:media-gateway-core-gluetun"
    volumes:
      - ./data:/data
