services:
  docker-proxy:
    image: tecnativa/docker-socket-proxy:v0.5.0
    container_name: docker-proxy
    network_mode: "container:utilities-gateway-gluetun"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - VOLUMES=1
      - NETWORKS=1
      - EVENTS=1
      - INFO=1
      - POST=0
      - DELETE=0
      - EXEC=0
      - BUILD=0
    restart: unless-stopped
