services:
  scrob-db:
    container_name: scrob-db
    image: postgres:16.15-alpine
    restart: unless-stopped
    network_mode: "container:media-gateway-stremio-utilities-gluetun"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  scrob:
    container_name: scrob
    image: bellamy/scrob:latest
    restart: unless-stopped
    network_mode: "container:media-gateway-stremio-utilities-gluetun"
    depends_on:
      scrob-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ENABLE_REGISTRATIONS: "${ENABLE_REGISTRATIONS}"
      REGISTRATION_MAX_ALLOWED_USERS: "${REGISTRATION_MAX_ALLOWED_USERS}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - ./data/scrob:/app/backend/data
