services:
  athenaeum:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8741/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: ghcr.io/bothari/athenaeum:latest
    container_name: athenaeum
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    network_mode: "container:media-gateway-comics-gluetun"
    volumes:
      - ./data:/data
      - ${MEDIA_SHARE}/media/Books:/output
      - ${MEDIA_SHARE}/downloads:/downloads
      - ${MEDIA_SHARE}:/share
    restart: unless-stopped
