services:
  unpackerr:
    image: golift/unpackerr:v0.16.1
    container_name: unpackerr
    volumes:
      - ${MEDIA_SHARE}:/share
    restart: unless-stopped
    user: ${PUID:-1000}:${PGID:-1000}
    network_mode: "container:media-gateway-core-gluetun"
    environment:
      - UN_START_DELAY=1m
      - TZ=${TZ}
      - UN_SONARR_0_URL=http://127.0.0.1:8989
      - UN_SONARR_0_API_KEY=${SONARR_KEY}
      - UN_SONARR_0_TIMEOUT=10s
      - UN_RADARR_0_URL=http://127.0.0.1:7878
      - UN_RADARR_0_API_KEY=${RADARR_KEY}
      - UN_RADARR_0_TIMEOUT=10s
