- Links:
    - GitHub Repo:
        - icon: github
          href: https://github.com/nt-louis/polaris
    - Homelab Wiki:
        - icon: wikipedia
          href: https://selfhosted.show/
    - Tailscale Admin:
        - icon: tailscale
          href: https://login.tailscale.com/
